---
title: "data_proceeding"
author: '@tabutan'
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(gt)
library(gtExtras)
library(DT)
library(webshot2)
```


```{r read data}
gori_zoo <- read_csv("DB_gorilla_zoo.csv") %>% 
  mutate("birthday" = ymd(birthday),  
         "this_year" = year(Sys.Date()),
         "endday" = make_date(this_year) - ddays(1),　#元日を作成し1日引いて大晦日にする
         "age" = trunc((birthday %--% endday)/years(1))
  )
```

```{r data editing}
gori_zoo %>%
  select(-this_year,-endday) %>%
  select(-origin, origin)    #origin列を右端に移動

df_age <- tibble(m = "m", f = "f", age = 0:60) %>% 
  pivot_longer(cols = c("m", "f"), names_to = "sex") %>% 
  select(-value) %>% 
  bind_rows(gori_zoo) %>% 
  mutate("N" = if_else(ID == "NA", 0,1)) %>% 
  group_by(age, sex) %>% 
  summarise("N" = sum(N, na.rm = TRUE)) %>% 
  filter(age <= 50) 


 # ggsave("figure/p_gori_pyramid.png", p_gori_pyramid, dpi = 600,
 #        width = 180, height = 90, units = "mm")

  
```

コードを少しいじった。参考にしたのは以下のものから。
https://onoshima.github.io/blog/2020/10/08/gt/
```{r}
likeapa_kai <- function(x){tab_options(x,
  table.border.top.width = 0, #タイトルの上の線を消す，
  table.border.bottom.width = 0, #注の下の線を消す
  heading.title.font.size = px(16), #タイトルのフォントサイズをいい感じに
  row_group.border.bottom.width = 0, #セクション名の下の線を消す
  table_body.hlines.width = 0, # tableの中の水平線消す
  stub.border.width = 0, # stub列の中の線を消す
  column_labels.border.top.width = 3, # 変数名の行の線を黒く太く
  column_labels.border.top.color = "black", 
  column_labels.border.bottom.width = 3,
  column_labels.border.bottom.color = "black",
  table_body.border.bottom.color = "black", #テーブルの下線を黒く
  table.width = pct(55), # 程よく幅を広げる（数字で調整）
  table.background.color = "white",
  row_group.border.top.color = "black", #セクション名の上の線を消す
  row_group.border.top.width = 1 #セクション名の上の線を細く
) %>% cols_align(align="center") %>%  # スタブ以外の列名を中央揃えに
  tab_style(
    style=list(cell_text(align="left")), # グループ変数名を中央揃えに
    locations=cells_row_groups()
  )}
```


```{r}
gori_zoo %>% 
  mutate("sex" = if_else(sex == "f", "メス", "オス"),   #文字列置換
         "zoo" = if_else(zoo == "chiba","千葉市動物公園",
                    if_else(zoo == "ueno","上野動物園",
                    if_else(zoo == "hamamatsu","浜松市動物園",
                    if_else(zoo == "higasiyama","東山動植物園",
                    if_else(zoo == "jmc","日本モンキーセンター",
                    if_else(zoo == "kyoto","京都市動物園",""))))))
         ) %>% 
  # group_by(zoo) %>%
  select(-this_year,-endday,-origin,-note,origin,note) %>% 
  mutate("ID" = if_else(ID == "monta","モンタ",
                        if_else(ID == "rora","ローラ",
                        if_else(ID == "haoko","ハオコ",
                        if_else(ID == "riki","リキ",
                        if_else(ID == "toto","トト",
                        if_else(ID == "momoko","モモコ",
                        if_else(ID == "komomo","コモモ",
                        if_else(ID == "momoka","モモカ",
                        if_else(ID == "sumomo","スモモ",
                        if_else(ID == "sho","ショウ",
                        if_else(ID == "nene","ネネ",
                        if_else(ID == "shabani","シャバーニ",
                        if_else(ID == "ai","アイ",
                        if_else(ID == "kiyomasa","キヨマサ",
                        if_else(ID == "anii","アニー",
                        if_else(ID == "taro","タロウ",
                        if_else(ID == "momotaro","モモタロウ",
                        if_else(ID == "genki","ゲンキ",
                        if_else(ID == "gentaro","ゲンタロウ",
                        if_else(ID == "kintaro","キンタロウ"
                                ,""))))))))))))))))))))) %>% 
   rename(" " = ID,
         "性別"= sex,
         "誕生日"=birthday,
         "備考"=note,
         "年齢"=age,
         "出自"=origin) %>% 
  group_by(zoo) %>% 
  gt() %>% 
  tab_header(title = "日本の動物園にいるゴリラ")  %>% 
  tab_footnote(footnote = "年齢は、前年の12月31日を基準に計算") %>% 
  tab_options(
    row.striping.include_table_body = TRUE
  ) %>% 
  tab_style(
    style = cell_text(color = "black", weight = "bold"),
    locations = list(
      cells_row_groups(),
      cells_column_labels(everything())
    )
    ) %>% 
  likeapa_kai %>% 
  gtsave("p_gori_member.png", path = "figure")

```

